CREATE DATABASE IF NOT EXISTS npm;
CREATE DATABASE IF NOT EXISTS prestashop;
CREATE DATABASE IF NOT EXISTS mautic;

GRANT ALL PRIVILEGES ON npm.* TO 'npmuser'@'%' IDENTIFIED BY 'tKYklV674308';
GRANT ALL PRIVILEGES ON prestashop.* TO 'psuser'@'%' IDENTIFIED BY 'zwL7483cGuJq';
GRANT ALL PRIVILEGES ON mautic.* TO 'muser'@'%' IDENTIFIED BY 'Wrb3Nf4z9vn9';